### ISSUE TITLE
Empirical Copula

### ISSUE THREAD

**Issue by Santymax98** [lrnv/Copulas.jl#105]
Hi, I wanted to ask if the Copula empirica pdf and cdf is working correctly or not yet. 

i used

`
emp = EmpiricalCopula(u)
den = pdf(emp, [0.5, 0.5])
`

ERROR: MethodError: no method matching _logpdf(::EmpiricalCopula{2, Adjoint{Float32, Matrix{Float32}}}, ::Vector{Float64})

`emp = EmpiricalCopula(u)
den = cdf(emp, [0.5, 0.5])`

ERROR: UndefVarError: `mean` not defined

**Comment by lrnv** [comment]
The pdf is normal as the empirical copula does not have a pdf. But the cdf part indeed looks like a bug.

**Comment by lrnv** [comment]
Could you provide the data u that you were using ? Or some mockup data ? Looks like there was Float32 implicated ?
