### ISSUE TITLE
Elliptical CDF

### ISSUE THREAD

**Issue by lrnv** [lrnv/Copulas.jl#15]
Gaussian and student have no cdf.

from discourse : https://discourse.julialang.org/t/cdf-of-a-copula-from-copulas-jl/85786

> I fixed `Copulas.jl` (in the latest master commit), so that it provides a more accurate error: we rely on `Distributions.jl`'s implementation of the multivariate Gaussian and Student distributions to handle the complexity behind the Gaussian and Student copulas, and `Distributions.jl` has no multivariate Gaussian `cdf`.
> Here is a Github issue for this : https://github.com/JuliaStats/Distributions.jl/issues/260
> Also, seems relevant there : https://github.com/JuliaStats/StatsFuns.jl/pull/114
> But it does not look like it is going to be fixed soon. If you find somewhere an integration routine that computes the `cdf` of a multivariate Gaussian, I am willing to include it as a temporary workaround though, until those issues are fixed in `StatsFun.jl` and `Distributions.jl`

**Comment by PharmCat** [comment]
Hi!

I think, it can be a concept for GaussianCopula:

```
using MvNormalCDF
using Copulas, Distributions

x = Normal(0, 1)
y = Normal(0, 2)
C = GaussianCopula([1 0.5; 0.5 1])
D = SklarDist(C, (x,y))

####
μ = mean.(D.m)
σ = collect(std.(D.m))
Σ = cor2cov(D.C.Σ, σ)
MvNormalCDF.mvnormcdf(μ, Σ, [-1.0, -2.0], [3.0, 4.0], m = 6000)
#(0.7216874201273508, 4.10731083253638e-5)
####
func(x) = pdf(D, [x[1], x[2]])
Cubature.pcubature(func, [-1.0, -2.0], [3.0, 4.0], reltol=sqrt(eps()))
#(0.7217122929674319, 8.450906641144229e-12)
```

**Comment by lrnv** [comment]
The `cdf` function already exists for `SklarDist` and depends on the `cdf` function of the `Copula` object. Therefore only the `cdf` functon of the copula object seems to be needed. I'll try with `MvNormalCDF` for the gaussian one for now, wait until my PR.
