### ISSUE TITLE
Something wrong with this reference?

### ISSUE THREAD

**Issue by osorensen** [lrnv/Copulas.jl#176]
Looks like you have multiple lines in `paper.bib` and that parts of a name is missing?

<img width="1232" alt="image" src="https://github.com/lrnv/Copulas.jl/assets/21175639/96cc9663-2d8c-4791-b0fe-970efaf49fd3">

https://github.com/openjournals/joss-reviews/issues/6189

**Comment by lrnv** [comment]
Loks like it is the expected output,; see there : https://zenodo.org/records/10412898.

**Comment by lrnv** [comment]
Oops should not have been closed before @osorensen validate.

**Comment by osorensen** [comment]
Indeed, it looks correct, whoever "amrods" is :-)
