### ISSUE TITLE
Can you recognize this one?

### ISSUE THREAD

**Issue by osorensen** [lrnv/Copulas.jl#177]
I'm not sufficiently acquainted with copulas to know if the comment "# can you recognize this one ?" should be there or not. Could you please explain what it means? It might well be fine.

<img width="960" alt="image" src="https://github.com/lrnv/Copulas.jl/assets/21175639/25e21cd6-9007-4a2d-89bd-e4d15d2a1ad2">

https://github.com/openjournals/joss-reviews/issues/6189

**Comment by lrnv** [comment]
This is the generator of the independent copula. Admitedly, this was a pun : if you end up reading this you should recognize it. But it might not be the right tone, you are right, I'll remove this.
