### ISSUE TITLE
[FR] : implementing derivatives for the Gumbel Generator

### ISSUE THREAD

**Issue by Santymax98** [lrnv/Copulas.jl#215]
Hi dear Oskar. 

Do you know why these errors of this type occur?

```julia
julia> G = GumbelCopula(2, 244.3966206319112)
GumbelCopula{2, Float64}(
G: Copulas.GumbelGenerator{Float64}(244.3966206319112)
)


julia> u = [0.969034207932297,0.9638122014293545]
2-element Vector{Float64}:
 0.969034207932297
 0.9638122014293545

julia> pdf(G, u)
ERROR: DomainError with  1.0 t + 𝒪(t³) :
The 0-th order Taylor1 coefficient must be non-zero
to raise the Taylor1 polynomial to a non-integer exponent.
Stacktrace:
  [1] pow!
    @ C:\Users\Pastor Jose Andres J\.julia\packages\TaylorSeries\wwiDC\src\power.jl:208 [inlined]
  [2] ^(a::TaylorSeries.Taylor1{Float64}, r::Float64)
    @ TaylorSeries C:\Users\Pastor Jose Andres J\.julia\packages\TaylorSeries\wwiDC\src\power.jl:111
  [3] ϕ(G::Copulas.GumbelGenerator{Float64}, t::TaylorSeries.Taylor1{Float64})
    @ Copulas C:\Users\Pastor Jose Andres J\.julia\packages\Copulas\SPHR4\src\Generator\UnivariateGenerator\GumbelGenerator.jl:40
  [4] ϕ⁽ᵏ⁾(G::Copulas.GumbelGenerator{Float64}, k::Int64, t::Float64)
    @ Copulas C:\Users\Pastor Jose Andres J\.julia\packages\Copulas\SPHR4\src\Generator.jl:40
  [5] ϕ⁽ᵏ⁾
    @ C:\Users\Pastor Jose Andres J\.julia\packages\Copulas\SPHR4\src\ArchimedeanCopula.jl:54 [inlined]
  [6] _logpdf(C::GumbelCopula{2, Float64}, u::Vector{Float64})
    @ Copulas C:\Users\Pastor Jose Andres J\.julia\packages\Copulas\SPHR4\src\ArchimedeanCopula.jl:76
  [7] logpdf
    @ C:\Users\Pastor Jose Andres J\.julia\packages\Distributions\ji8PW\src\common.jl:263 [inlined]
  [8] _pdf
    @ C:\Users\Pastor Jose Andres J\.julia\packages\Distributions\ji8PW\src\common.jl:237 [inlined]
  [9] pdf(d::GumbelCopula{2, Float64}, x::Vector{Float64})
    @ Distributions C:\Users\Pastor Jose Andres J\.julia\packages\Distributions\ji8PW\src\common.jl:222
 [10] top-level scope
    @ REPL[3]:1
```

**Comment by lrnv** [comment]
Numerical derivations issues at extreme values (244 is in one sense too close to infinity). There is an easy fix for the Gumbel case, which would simply require "filling out" the derivatives manually in `src/Generator/UnivariateGenerator/GumbelGenerator.jl` line 42 and 43 there : 

https://github.com/lrnv/Copulas.jl/blob/0d4d86361f84fe0ec9bd15e86f282866d5816886/src/Generator/UnivariateGenerator/GumbelGenerator.jl#L42-L43

I thnk there exists analytic formula for these derivatives, and implementing them here would remove this bug

**Comment by Santymax98** [comment]
I did it in the package I developed and I noticed that NaN appears, so I don't know how to solve it

`dϕ(C::GumbelCopula, t) = - (1 / C.θ) * t^(1 / C.θ - 1) * exp(-t^(1 / C.θ))`

**Comment by lrnv** [comment]
The problem us not the first one but the second and third ones. Try it here to see if you have the same nans ? If yes, I'll investigate

**Comment by lrnv** [comment]
Another OK solution is to completely specialty the `_logpdf` function for Gumbel copula instead of using the generic archimedean one : doing computation by hand might give simplifications that the computer has toru le doing numerically

**Comment by Santymax98** [comment]
I'm going to work a little on the `_logpdf`, I think we can use the properties in Nelsen to determine a general `_logpdf` if not, I should use a specific one for the bivariate case. by gumbel.

**Comment by lrnv** [comment]
Yes, you can also specialize on the dimension since it is part of the type itself. Do I wait for your pr ?
