### ISSUE TITLE
Move from Cubature to HCubature to avoid GPL dependency?

### ISSUE THREAD

**Issue by andreasnoack** [lrnv/Copulas.jl#235]
The package currently depends on the GPL licensed Cubature package. Do you think it would be feasible to switch to HCubature to avoid that?

**Comment by lrnv** [comment]
@andreasnoack There was a fix proposed by @DilumAluthge at #236, this should be fixed in v0.1.26 released in a few minuts. Do not hesitate to reopen if needed. Thanks for the remark :)
