### ISSUE TITLE
Lack of documentation on PlackettCopula

### ISSUE THREAD

**Issue by lrnv** [lrnv/Copulas.jl#42]
@Santymax98 I did not check on the pull-request, but you did not write the documentation of the new copula type as the other ones (granted, some of them are missing). 

Would you like to do it yourself ? Copy the format of the documentation from some other copula model, and include in it your references. 

Or do you prefer me to do it ?

**Comment by Santymax98** [comment]
Hi,


I didn't know I should do it. I can do it myself, however I'm not really
sure how to do it. Could you tell me how to do it?


Yesterday I was working on Archimedean copulas. However, I think I will not
be able to use the same sampling algorithm since I cannot find the radial
distribution.

**Comment by lrnv** [comment]
To make the documentation, you simply need to add triple backtics comments on top of the functions. See e.g. for the clayton copula there : https://github.com/lrnv/Copulas.jl/blob/main/src/ArchimedeanCopulas/ClaytonCopula.jl

I am working on another better sampling algorithm (McNeil Neshleova) using the williamson d-transform, that should work for any archimedean copula. You may take a look at the pacage there : https://github.com/lrnv/williamsontransform.jl and the reference : 

@article{mcneil2009multivariate,
  title={Multivariate Archimedean copulas, d-monotone functions and ℓ 1-norm symmetric distributions},
  author={McNeil, Alexander J and Ne{\v{s}}lehov{\'a}, Johanna},
  year={2009}
}

By using this transformation, we will then be able to sample every archimedean copulas, the implementation should come soon when i have some time.

**Comment by lrnv** [comment]
Hey thanks a lot for the documentation. I'll close this issue and open another one to discuss the move to williamson transformations instead and/or together with frailty models for archimedean sampling
