### ISSUE TITLE
problem with Copula Frank samples

### ISSUE THREAD

**Issue by Santymax98** [lrnv/Copulas.jl#64]
Hi, I had a very strange problem, when I want to sample the two-dimensional Frank copula I get infinite values.

`` F = FrankCopula(2,98.11)``
`` r = rand(F,1)``
Just with one value, it is giving infinity

I also tried with parameters like 86.44 and 75.

**Comment by Santymax98** [comment]
I realized that if you use a parameter greater than or equal to 38 the samples start to come out infinite.

**Comment by lrnv** [comment]
Another option (the one chosen by the R package) is to just give up and furnish `MCopula` samples instead for theta > 38 ( they also have a hardcoded 38 there, you did find the right value). But I am not sure I am willing to do that without at least a warning..

**Comment by Santymax98** [comment]
I am working with dynamic copulas, that is, the parameter can change over time and in the simulations it gives some parameters a little greater than 30, I think that for now I will use the BigFloat option, it is strange that for very small negative values, for example -120 he gives samples without problems

**Comment by lrnv** [comment]
Did you took a look at those samples ? They might not be very good ones. In #65 I am actually adding a test on uniformity of marginals to check for these kind of stuff more seriously in the future.
