### ISSUE TITLE
Inverse Gaussian Copula 

### ISSUE THREAD

**Issue by Santymax98** [lrnv/Copulas.jl#66]
Hi!!, 

In the Gaussian inverse copula when the parameter is zero it should return the independent copula (special case) as the verification is below the requirement that the parameter must be positive it is removing the opportunity to return the independent copula when the parameter is equal to zero

**Comment by Santymax98** [comment]
Hello, I noticed that the Gumbel copula does not allow obtaining samples larger than copulas with a parameter greater than 10, since the ``\alpha - stable`` distribution has a limitation of 0.1 to 2 and I think it should be ``0 < \alpha < 1``

**Comment by lrnv** [comment]
The invgaussian is fixed in #67. But the Gumbel indeed that is probably a limitation of the current algorithm. I will investigate a bit (but in a new issue, please a topic per problem)
