### ISSUE TITLE
pdf/logpdf for Archimedean copula

### ISSUE THREAD

**Issue by mlkrock** [lrnv/Copulas.jl#7]
Looking at R copula library, the calculation of the pdf/logpdf is quite a pain.

If you don't mind the dependency, could use ForwardDiff.jl to get the derivatives of the generator, then everything is pretty easy. The main question is how to get the  higher order derivatives, I see some discussion e.g. https://discourse.julialang.org/t/automatic-differentiation-for-higher-order-derivatives/62337.
https://discourse.julialang.org/t/forwarddiff-3rd-or-even-higher-order-derivatives/8011/6
The easy option is to just write 

`∂ϕ(cop::CT, t::Real) where {CT<:Copulas.ArchimedeanCopula} = ForwardDiff.derivative(x -> Copulas.ϕ(cop,x),t)
∂²ϕ(cop::CT, t::Real) where {CT<:Copulas.ArchimedeanCopula} = ForwardDiff.derivative(x -> ∂ϕ(cop,x), t)
`
etc. There might be a smarter way to do this, but I don't see anything obvious. Since, you only need the d'th and first derivative  of the generator for the pdf, it may be fine for now, but there's probably some way to get the first derivative along the way to the d'th derivative.

The R library also stops after d=6 for Archimedean, so could follow that convention, since at some point Archimedean in high dimension is silly.

**Comment by lrnv** [comment]
What I remember without taking a look at it is that the number of derivatives you need is more or less the dimension of the model. Therefore, my ambition was to use ForwardDiff for the *default* implementation on `ArchimedeanCopula`s, as you point out. Feel free to implement it and PR if you want, otherwise I'll do it this summer. No need to stop arbitrarily at d=6, I plan to just let it be generic.

**Comment by mlkrock** [comment]
I just made a PR but I stopped at d=9, so can already say it's better than R there, but I'm not sure of a way to make it a derivative for  general dimension d.

**Comment by lrnv** [comment]
Hey ! I commented on the PR, let's discuss the implementation details there. 

The Joe problem should maybe become a test case ? I agree with you that this is not satisfactory, as 1/1000 quantiles are sometimes needed when dealing with extremal problems (and therefore should be accurate).
