### ISSUE TITLE
Doubt about the Williamson transform

### ISSUE THREAD

**Issue by Santymax98** [lrnv/Copulas.jl#76]
Dear Oskar 

I hope everething ok.

I wanted to ask you something regarding your implementation of the Williamson transform. Is it possible to obtain the accumulated function "quantile()" for the Radial function of the Archimedean family provided by the implementation?

**Comment by lrnv** [comment]
Yes it is possible of course, the easiest way would be to juste invert the CDF by using Roots.jl. You could add it yourself by pushing a PR onto https://github.com/lrnv/WilliamsonTransforms.jl or just wait until tomorrow and I'll do it

**Comment by Santymax98** [comment]
Thanks, I will!

**Comment by lrnv** [comment]
This is done I close this then
