### ISSUE TITLE
[Bug] Kendall's tau for TCopula & non-archimedeans more generally

### ISSUE THREAD

**Issue by Santymax98** [lrnv/Copulas.jl#80]
Hello, when I try to calculate the kendal tau of any copula, it appears that it is not defined
`julia> Σ = [1.0 0.8; 0.8 1.0]
2×2 Matrix{Float64}:
 1.0  0.8
 0.8  1.0

julia> Cop = GaussianCopula(Σ)
GaussianCopula{2, Matrix{Float64}}(
Σ: [1.0 0.8; 0.8 1.0]
)

julia> τ(Cop)
ERROR: UndefVarError: `τ` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1`

**Comment by lrnv** [comment]
Indeed it is not. There is no default implementation, the archimedean copulas have their implementation but the elliptical ones have none. 

Do you want to provide a default implementation ? As $\tau(C) = 4 * Expectation (C(U)) - 1$ for $U \sim C$ ? You may use `Distributions.expectation()` as is done at several other places in the package.

**Comment by Santymax98** [comment]
Does it mean that I can't calculate Kendall's tau for an Archimedean copula either?

`julia> C = ClaytonCopula(2,1.5)
ClaytonCopula{2, Float64}(θ=1.5)

julia> τ(C)
ERROR: UndefVarError: `τ` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[10]:1

julia> `

**Comment by lrnv** [comment]
The function exists but is not exported yet : 

```julia
julia> using Copulas

julia> C = ClaytonCopula(2,10)
ClaytonCopula{2, Int64}(
G: Copulas.ClaytonGenerator{Int64}(10)
)


julia> Copulas.τ(C)
0.8333333333333334

julia> τ(C)
ERROR: UndefVarError: `τ` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[8]:1

julia> 
```

**Comment by lrnv** [comment]
Btw in fact it already works for the gaussian : 

```julia
julia> C = GaussianCopula([1 0.5; 0.5 1])
GaussianCopula{2, Matrix{Float64}}(
Σ: [1.0 0.5; 0.5 1.0]
)


julia> Copulas.τ(C)
0.16834795498215338

julia> 
```

**Comment by Santymax98** [comment]
Now I got it, however, what copulations is it missing for? It would be good to implement it together with Sperman's Rho

**Comment by lrnv** [comment]
The implementation is there : https://github.com/lrnv/Copulas.jl/blob/d7cf205c00bd1e40525d0e602b79fd5c26bdac10/src/Copula.jl#L24-L35

But it is not well tested for the moment. What we could do is add some tests.

**Comment by Santymax98** [comment]
I understand, that function is general. At least for now it can be used. You could try the copula T, I think it is giving some Nan values

`julia> Copa=TCopula(4,Σ)
TCopula{2, 4, Matrix{Float64}}(
Σ: [1.0 0.8; 0.8 1.0]
)


julia> Copulas.τ(Copa)
NaN`

**Comment by Santymax98** [comment]
Understood, thank you very much for the suggestion and for answering the Issue.
